qonto/ember-lottie

- .github/workflows/release.yml
- CHANGELOG.md
- README.md
- RELEASE.md
- package-lock.json
- package.json
Install and configure release-it
* run `npm init rwjblue-release-it-setup`
* setup github publish workflow
* add README.md npmjs badges
* update install instructions to use `@qonto` namespace
[Rendered README.md](https://github.com/qonto/ember-lottie/blob/043941114837229a3f0a0d2058fc3ed56199b72f/README.md), the npmjs badge will show `invalid` until the first release
> Add release mechanism

- addon/components/lottie.hbs
- addon/components/lottie.ts
- package-lock.json
- package.json
- tests/integration/components/lottie-test.ts
👇👇👇
> **WARNING:** the `autoplay` property should be actually renamed to something like `preferredAutoplay` because it can be ignored depending on the value of the `prefers-reduced-motion` media query. I decided to avoid this change now, because it will break existing clients. We can do it on a separate PR
☝️ ☝️ ☝️ 
This PR introduces a default value for the `autoplay` prop, by taking into account the `prefers-reduced-motion` [media query](https://web.dev/prefers-reduced-motion/).
If the host application doesn't specify `@autoplay={{true}}`, the component checks the user preference about motion, if no preference has been given, the component will autoplay the animation; otherwise, if the user prefers reduced motion, the animation won't play. It will follow a similar logic when …
> Modify autoplay default by taking into account prefers-reduced-motion

- addon/components/lottie.ts
- package-lock.json
- package.json
- tests/integration/components/lottie-test.ts
In this pull request we set up [ember-test-waiters](https://github.com/emberjs/ember-test-waiters) to be able to add a waiter in the `animate` function to wait for async operations to complete before continuing tests.
See. https://github.com/qonto/ember-lottie/issues/20
> Add ember test waiters waiter in animate function

- addon/components/lottie.ts
- tests/integration/components/lottie-test.ts
This PR fixes a bug related to the usage of the `containerId` parameter.
If the `containerId` wasn't passed explicitly to the component, then its value would have been `undefined`, which resulted in the DOM searching for an id `#undefined` (passed to `document.querySelector`). 
We want to be sure that when no `containerId` is passed, no call to `document.querySelector` will be done. Wrote a test to make sure that this doesn't happen again.
> Fixed container option to avoid searching the DOM for undefined containerId

- package.json
Adding `release-it` to package.json `scripts`, so that we can release with `npm run release`.
> Add release-it script to package.json

- package-lock.json
- package.json
So I don't get warnings in consuming app when doing a fresh `pnpm i`
```sh
 WARN  Issues with peer dependencies found
.
├─┬ @qonto/ember-lottie 0.4.0
│ ├─┬ @typescript-eslint/eslint-plugin 5.57.0
│ │ ├── ✕ missing peer typescript@"*"
│ │ └─┬ @typescript-eslint/type-utils 5.57.0
│ │   ├── ✕ missing peer typescript@"*"
│ │   └─┬ @typescript-eslint/typescript-estree 5.57.0
│ │     ├── ✕ missing peer typescript@"*"
│ │     └─┬ tsutils 3.21.0
│ │       └── ✕ missing peer typescript@">=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta"
│ └─┬ @typescript-eslint/parser 5.57.0
│   └── ✕ missing peer typescript@"*"
```
> Move eslint deps to devDependencies

- .github/workflows/ci.yml
- ember-lottie/package.json
- pnpm-lock.yaml
In this MR, we make some updates to our CI script, because we now use `NullVoxPopuli/action-setup-pnpm` and it already:
- handles the node setup (so we were running `actions/setup-node` twice)
- calls `pnpm install` and [expose an `args` input](https://github.com/NullVoxPopuli/action-setup-pnpm#args) (so we were running `pnpm install` command twice)
We had to add some @babel plugins to avoid getting unresolved module errors during the setup.
> Remove unnecessary jobs in CI script

- .github/dependabot.yml
We've got a bunch of dependabot PRs failing due to the lock file not being updated. The issue describes the change to configuration in this PR  https://github.com/dependabot/dependabot-core/issues/4993
> Auto update lock file with dependabot PRs

- .github/workflows/ci.yml
- pnpm-lock.yaml
The aim of this MR is using `wyvox/action-setup-pnpm@v3` in place of `NullVoxPopuli/action-setup-pnpm@v2` in our CI script.
`NullVoxPopuli/action-setup-pnpm` has been [archived](https://github.com/NullVoxPopuli/action-setup-pnpm) and moved to [another repository](https://github.com/wyvox/action-setup-pnpm).
> Update action-setup-pnpm to v3

- .github/workflows/ci.yml
This PR is a sort of a follow up to this other PR: https://github.com/qonto/ember-lottie/pull/202
In this PR I am using the correct syntax for the `no-lockfile` option. Sorry for the confusion.
> Use correct syntax for no-lockfile option

- .github/workflows/ci.yml
- ember-lottie/package.json
- pnpm-lock.yaml
- test-app/config/ember-try.js
- test-app/package.json
In this MR, `ember-source` was bumped from from version ~4.11.0 to ~5.3.0.
Testing scenarios were updated with the relevant LTS versions.
> feat(dev-deps): upgrade ember-source from ~4.11.0 to ~5.3.0

- pnpm-lock.yaml
- test-app/package.json
Wit this PR, @embroider/test-setup is bumped from 2.1.1 to 3.0.2.
This PR substitutes following expired Dependabot MR: https://github.com/qonto/ember-lottie/pull/116
> feat(dev-deps): Bump @embroider/test-setup from 2.1.1 to 3.0.2 in /test-app

- ember-lottie/package.json
- pnpm-lock.yaml
The aim of this PR is bumping [@typescript-eslint/parser](https://www.npmjs.com/package/@typescript-eslint/parser) in `/ember-lottie` from version 5.59.6  to 6.7.4.
This PR substitutes following Dependabot PR: https://github.com/qonto/ember-lottie/pull/152
> chore(deps-dev): bump @typescript-eslint/parser in /ember-lottie

- ember-lottie/package.json
- pnpm-lock.yaml
The aim of this PR is bumping [@glint/environment-ember-loose](https://www.npmjs.com/package/@glint/environment-ember-loose) from 0.9.7 to 1.2.1.
This PR substitutes following Dependabot PR: https://github.com/qonto/ember-lottie/pull/121
> Bump @glint/environment-ember-loose from 0.9.7 to 1.2.1 in /ember-lottie

- ember-lottie/package.json
- pnpm-lock.yaml
The aim of this PR is bumping [@glint/core](https://www.npmjs.com/package/@glint/core) from 0.9.7 to 1.2.1 in `/ember-lottie`.
This PR substitutes following Dependabot PR: https://github.com/qonto/ember-lottie/pull/125
> chore(deps-dev): bump @glint/core from 0.9.7 to 1.2.1 in /ember-lottie

- ember-lottie/package.json
- pnpm-lock.yaml
The aim of this PR is bumping [eslint-plugin-ember](https://www.npmjs.com/package/eslint-plugin-ember) from 10.6.1 to 11.11.1.
This PR substitutes the following Dependabot PR: https://github.com/qonto/ember-lottie/pull/133
> chore(deps-dev): bump eslint-plugin-ember from 10.6.1 to 11.11.1 in /ember-lottie

- ember-lottie/package.json
- pnpm-lock.yaml
The aim of this PR is bumping [@babel/core](https://www.npmjs.com/search?q=babel%2Fcore) from 7.21.3 to 7.23.0 in `/ember-lottie`
This PR substitutes following Dependabot MR: https://github.com/qonto/ember-lottie/pull/143/commits
> chore(deps-dev): bump @babel/core from 7.21.3 to 7.23.0 in /ember-lottie

- ember-lottie/package.json
- pnpm-lock.yaml
The aim of this PR is bumping [concurrently](https://www.npmjs.com/package/concurrently) from 7.6.0 to 8.2.1 in `/ember-lottie`
This PR substitutes following Dependabot PR: https://github.com/qonto/ember-lottie/pull/144
> chore(deps-dev): bump concurrently from 7.6.0 to 8.2.1 in /ember-lottie

- ember-lottie/package.json
- pnpm-lock.yaml
The aim of this PR is bumping [@babel/plugin-proposal-decorators](https://www.npmjs.com/search?q=%40babel%2Fplugin-proposal-decorators) from 7.21.0 to 7.23.0 in `/ember-lottie`.
This PR substitutes following Dependabot PR: https://github.com/qonto/ember-lottie/pull/145/commits
> chore(deps-dev): bump @babel/plugin-proposal-decorators from 7.21.0 to 7.23.0 in /ember-lottie

- ember-lottie/package.json
- pnpm-lock.yaml
The aim of this PR is bumping [@typescript-eslint/eslint-plugin](https://www.npmjs.com/package/@typescript-eslint/eslint-plugin) from 5.59.6 to 6.7.4 in `/ember-lottie`
This PR substitutes following Dependabot PR: https://github.com/qonto/ember-lottie/pull/150
> chore(deps-dev): bump @typescript-eslint/eslint-plugin from 5.59.6 to 6.7.4 in /ember-lottie

- pnpm-lock.yaml
- test-app/package.json
The aim of this PR is updating ember-cli from `4.11.0` to `4.12.2`. This is the highest `ember-cli` version we want to support.
> chore(deps-dev): bump ember-cli from 4.11.0 to 4.12.2 in /test-app

- README.md
In this PR, we remove 2 unused columns in the API reference table in the README.
To see the changes, you can compare the [master version](https://github.com/qonto/ember-lottie/tree/main#arguments) with [this branch version](https://github.com/qonto/ember-lottie/tree/fix-api-reference-table#arguments).
> fix(docs): remove unused columns in API reference table

- ember-lottie/.eslintrc.js
- ember-lottie/package.json
- pnpm-lock.yaml
- test-app/.eslintrc.js
- test-app/package.json
Install and use our custom ESLint configuration found on https://github.com/qonto/eslint-config-typescript.
The currently available version is a RC (Release Candidate) that we're testing on our public repos before making it stable.
We also regenerate the lock file to allow `pnpm` to do some optimizations, because of previous failing embroider jobs. We followed the recommendations described [here](https://github.com/embroider-build/embroider/blob/main/docs/peer-dependency-resolution-issues.md#how-can-i-workaround-these-problems) by embroider.
> chore: install and use @qonto/eslint-config-typescript@1.0.0-rc.0

- ember-lottie/src/components/lottie.ts
- test-app/tests/integration/components/lottie-test.ts
The aim of this PR is adding backward compatibility with `MediaQueryList.addEventListener` to older browsers that don't support it, e.g. Safari versions below 14 (released on 16/09/2020), as visible in the [MDN MediaQueryList browser compatibility chart](https://developer.mozilla.org/en-US/docs/Web/API/MediaQueryList#browser_compatibility).
Quoting from the [MDN MediaQueryList docs](https://developer.mozilla.org/en-US/docs/Web/API/MediaQueryList#browser_compatibility): 
- > [addListener()](https://developer.mozilla.org/en-US/docs/Web/API/MediaQueryList/addListener):  [...] This method exists primarily for backward compatibility; if possible, you should instead use [addEventListener()](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener) to watch for the …
> Add backward compatibility with MediaQueryList.addEventListener in older browsers

- README.md
- ember-lottie/src/components/lottie.ts
- test-app/tests/integration/components/lottie-test.ts
Rebased and cleaned up from https://github.com/qonto/ember-lottie/pull/131
Fetch request is failing with 403 when trying to fetch lottie json hosted on another domain that gates the assests behind credentials. https://javascript.info/fetch-crossorigin#credentials
> fix(lottie.ts): passing credentials include param to fetch request

- .github/workflows/ci.yml
- README.md
- package.json
- test-app/package.json
In this PR, `ember-lottie` gets no more support for node v14 and v16. Node v18 becomes the earliest supported version as it is still active for now.
Node v14 and v16 have no more active and security support. See https://endoflife.date/nodejs for more info.
The compatibility section of the package in the `README` is updated to inform node v18 or above is supported.
> feat: drop node v16

- .github/workflows/ci.yml
- ember-lottie/package.json
- pnpm-lock.yaml
- test-app/package.json
In this PR, we update `typescript` from `v5.2.2` to latest `v5.3.2`. We also add a new job for type checking the addon using TypeScript v5.2.
> chore(deps-dev): bump typescript from 5.2.2 to 5.3.2

- commitlint.config.js
Since Dependabot commit messages body line lengths do not conform with `commitlint`’s current limit of 100 characters, we are modifying the rule to accept an infinite number of characters.
The reasons behind this:
- Relying on the commit body from a third party is fragile; if Dependabot updates its wording, we have to update the override
- Bumping to a fixed char limit is also not the best, could fail sometimes, we would be stuck (re-)bumping the limit every time
- Commit body is actually not used in the changelog generation, so it won’t change much in the end
> Set body-max-line-length to Infinity

- .release-it.js
- RELEASE.md
- package.json
- pnpm-lock.yaml
In this PR, we replace  `@release-it-plugins/lerna-changelog` with `@release-it/conventional-changelog` in order to leverage Conventional Commit messages and update the CHANGELOG seamlessly.
This makes the entire process even more straightforward, as no preparation work is required ahead of a new release.
The process has been tested locally, attempting a sample release with dummy features and a breaking change. CHANGELOG and versions would have been updated as expected.
> Set up Conventional Changelog plugin for release-it

- pnpm-lock.yaml
This PR updates the lockfile after merging Babel-related dev dependency updates.
It fixes the following warning appearing when running `pnpm install`:
```bash
WARN  Broken lockfile: no entry for '/@babel/plugin-proposal-decorators/7.23.3(@babel/core@7.23.3)' in pnpm-lock.yaml
```
> Update broken lockfile

- ember-lottie/src/components/lottie.ts
- test-app/tests/integration/components/lottie-test.ts
We're getting Sentry errors reporting `Cannot read properties of undefined (reading 'headers')` originating from this fetch. This commit checks we have `fetchOptions` before invoking `fetch` with the `fetchOptions` otherwise only the path is used.
https://qonto.sentry.io/issues/4716260540/events/5a60659334a94c3e9e354542c5ceadf6/
> fix: dont pass undefined options to fetch

- .github/workflows/release.yml
- .release-it.js
- pnpm-lock.yaml
This PR adds a new workflow to delegate the package release to the CI.
The workflow can be dispatched only manually and will perform the following steps:
- Check out the code, including all history for all branches and tags.
- Verify that the workflow is triggered for the `main` branch, and abort if not.
- Set the Git user name and email to the person (or app) that initiated the workflow.
- Install dependencies.
- Trigger the release script.
> Add release workflow

- .release-it.js
Disabling `npm` on the root configuration for `release-it` should help us solve [this problem](https://github.com/qonto/ember-lottie/actions/runs/7349402643/job/20009262612#step:6:23), where multiple processes (`release-it` itself + `@release-it/workspaces`) try to bump the `npm` version by running `npm version` ending up in conflicts.
> chore(release-it): set npm as false on the root

- .release-it.js
- pnpm-lock.yaml
Adding the pnpm install hook to the conf to avoid [the outdated pnpm-lockfile problem](https://github.com/qonto/ember-lottie/actions/runs/7357391404/job/20028954115?pr=357#step:3:134).
> chore(release-it): add pnpm install hook in the conf

- .release-it.js
We couldn't create the previous GitHub release through the `Release` action, because we had the wrong `tokenRef` inside the release-it conf. By removing it, we'll use the default one - that's the one correctly set.
> chore(release-it): remove tokenRef from configuration

- .github/workflows/ci.yml
The `@next` tag is experimental and currently breaks type checking in CI. `@latest` means the latest **stable** version, which is enough for future proofing types.
> Use latest instead of next in typecheck job
